// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// hashtagsDao is the data access object for the table hg_hashtags.
// You can define custom methods on it to extend its functionality as needed.
type hashtagsDao struct {
	*internal.HashtagsDao
}

var (
	// Hashtags is a globally accessible object for table hg_hashtags operations.
	Hashtags = hashtagsDao{internal.NewHashtagsDao()}
)

// Add your custom methods and functionality below.
