// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// musicsDao is the data access object for the table hg_musics.
// You can define custom methods on it to extend its functionality as needed.
type musicsDao struct {
	*internal.MusicsDao
}

var (
	// Musics is a globally accessible object for table hg_musics operations.
	Musics = musicsDao{internal.NewMusicsDao()}
)

// Add your custom methods and functionality below.
