// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// suggestWordsDao is the data access object for the table hg_suggest_words.
// You can define custom methods on it to extend its functionality as needed.
type suggestWordsDao struct {
	*internal.SuggestWordsDao
}

var (
	// SuggestWords is a globally accessible object for table hg_suggest_words operations.
	SuggestWords = suggestWordsDao{internal.NewSuggestWordsDao()}
)

// Add your custom methods and functionality below.
