// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// videoHashtagDao is the data access object for the table hg_video_hashtag.
// You can define custom methods on it to extend its functionality as needed.
type videoHashtagDao struct {
	*internal.VideoHashtagDao
}

var (
	// VideoHashtag is a globally accessible object for table hg_video_hashtag operations.
	VideoHashtag = videoHashtagDao{internal.NewVideoHashtagDao()}
)

// Add your custom methods and functionality below.
