// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// videoMusicDao is the data access object for the table hg_video_music.
// You can define custom methods on it to extend its functionality as needed.
type videoMusicDao struct {
	*internal.VideoMusicDao
}

var (
	// VideoMusic is a globally accessible object for table hg_video_music operations.
	VideoMusic = videoMusicDao{internal.NewVideoMusicDao()}
)

// Add your custom methods and functionality below.
