// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// videoSuggestWordDao is the data access object for the table hg_video_suggest_word.
// You can define custom methods on it to extend its functionality as needed.
type videoSuggestWordDao struct {
	*internal.VideoSuggestWordDao
}

var (
	// VideoSuggestWord is a globally accessible object for table hg_video_suggest_word operations.
	VideoSuggestWord = videoSuggestWordDao{internal.NewVideoSuggestWordDao()}
)

// Add your custom methods and functionality below.
