// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// videosDao is the data access object for the table hg_videos.
// You can define custom methods on it to extend its functionality as needed.
type videosDao struct {
	*internal.VideosDao
}

var (
	// Videos is a globally accessible object for table hg_videos operations.
	Videos = videosDao{internal.NewVideosDao()}
)

// Add your custom methods and functionality below.
